### ISSUE TITLE
Ability to share state between local machine and docker image

### ISSUE THREAD

**Issue by snowch** [hpe-container-platform-community/ezdemo#3]
I'm wondering whether a simple fix for this requirement could be to mount two volumes and use two rsync processes.

One process would copy config files allowing users to provide only the files they need to change, e.g.

If on the host (rsync source) you had  `./app/server/aws/config.json` rsync's default behavior would be to copy only the files on the source without deleting the other files in the destination.

rsync could also be used to create a backup of the entire docker /app folder to the local machine?

Thoughts?

**Comment by erdincka** [comment]
First thought is to use a volume, attaching config.json to the container. User needs to create config.json locally and then start the container with volume mapping.  
Another option is to use ENV variables to pass credentials (and possibly other options) for config.json. This can be used to pass on credentials and username from the user starting the container. User can export vars or we can read credentials from their default location (~/.aws/...).
Both can be done with the script provided (./docker-run.sh).
Which provides the better user experience?

**Comment by erdincka** [comment]
Let's think about how to handle multiple user configuration settings. config.json is inside the provider directory. will be different for each provider (Vmware, AWS, Azure etc). Depending on provider selection, different settings/params will be required (ie, vcenter details for Vmware, different credentials such as appId/appsecret for Azure).

**Comment by erdincka** [comment]
start docker container in the same folder with json files, ie, aws_config.json, azure_config.json etc (for specific provider name, underscore, and config.json as file name). start.sh script will mount these files under target provider folder(s).

**Comment by snowch** [comment]
Nice :) 

Thanks, Erdinc!
